#pragma strict

///// Codigos de tempo
/// 0 - Ceu Limpo
/// 1 - Ceu nublado
/// 2 - Chuva
/// 3 - Chuva e trevoada
static var TempoActual=1;
///////////////////////
var timer=244;


var Clouds:GameObject;
var Trevoada:GameObject;
var ChuvaPC:GameObject;
var ChuvaTablet:GameObject;
var IsPC=true;

function Start () {
	timer=3;
	TempoActual=Random.Range(0,8);
	if(Application.platform==RuntimePlatform.Android || Application.platform==RuntimePlatform.IPhonePlayer)
	{
		IsPC=false;
	}
}

function Update () {
	if(Network.peerType==NetworkPeerType.Disconnected){
		timer=timer-1;
		if(timer==0)
		{
			TempoActual=Random.Range(0,8);
			timer=Random.Range(1000,30000);
			if(TempoActual==1)
			{
				Clouds.GetComponent.<AudioSource>().volume=0;
				Clouds.active=false;
				Trevoada.active=false;
				if(IsPC)
				{
					ChuvaPC.active=false;
				}
				else
				{
					ChuvaTablet.active=false;
				}
			}
			if(TempoActual==2)
			{
				Clouds.GetComponent.<AudioSource>().volume=0;
				Clouds.active=true;
				Trevoada.active=false;
				if(IsPC)
				{
					ChuvaPC.active=false;
				}
				else
				{
					ChuvaTablet.active=false;
				}
			}
			if(TempoActual==3)
			{
				Clouds.GetComponent.<AudioSource>().volume=0.06;
				Clouds.active=true;
				Trevoada.active=false;
				if(IsPC)
				{
					ChuvaPC.active=true;
				}
				else
				{
					ChuvaTablet.active=true;
				}
			}
			if(TempoActual==0)
			{
				Clouds.GetComponent.<AudioSource>().volume=0.2;
				Clouds.active=true;
				Trevoada.active=true;
				if(IsPC)
				{
					ChuvaPC.active=true;
				}
				else
				{
					ChuvaTablet.active=true;
				}
			}
		}
	}else{
		if(Network.isServer){
			timer=timer-1;
			if(timer==0)
			{
				TempoActual=Random.Range(0,8);
				timer=Random.Range(1000,30000);
				GetComponent.<NetworkView>().RPC("GetServerWeather",RPCMode.All,TempoActual);
				if(TempoActual==1)
				{
					Clouds.GetComponent.<AudioSource>().volume=0;
					Clouds.active=false;
					Trevoada.active=false;
					if(IsPC)
					{
						ChuvaPC.active=false;
					}
					else
					{
						ChuvaTablet.active=false;
					}
				}
				if(TempoActual==2)
				{
					Clouds.GetComponent.<AudioSource>().volume=0;
					Clouds.active=true;
					Trevoada.active=false;
					if(IsPC)
					{
						ChuvaPC.active=false;
					}
					else
					{
						ChuvaTablet.active=false;
					}
				}
				if(TempoActual==3)
				{
					Clouds.GetComponent.<AudioSource>().volume=0.06;
					Clouds.active=true;
					Trevoada.active=false;
					if(IsPC)
					{
						ChuvaPC.active=true;
					}
					else
					{
						ChuvaTablet.active=true;
					}
				}
				if(TempoActual==0)
				{
					Clouds.GetComponent.<AudioSource>().volume=0.2;
					Clouds.active=true;
					Trevoada.active=true;
					if(IsPC)
					{
						ChuvaPC.active=true;
					}
					else
					{
						ChuvaTablet.active=true;
					}
				}
			}
		}else{
			if(TempoActual==1)
			{
				Clouds.GetComponent.<AudioSource>().volume=0;
				Clouds.active=false;
				Trevoada.active=false;
				if(IsPC)
				{
					ChuvaPC.active=false;
				}
				else
				{
					ChuvaTablet.active=false;
				}
			}
			if(TempoActual==2)
			{
				Clouds.GetComponent.<AudioSource>().volume=0;
				Clouds.active=true;
				Trevoada.active=false;
				if(IsPC)
				{
					ChuvaPC.active=false;
				}
				else
				{
					ChuvaTablet.active=false;
				}
			}
			if(TempoActual==3)
			{
				Clouds.GetComponent.<AudioSource>().volume=0.06;
				Clouds.active=true;
				Trevoada.active=false;
				if(IsPC)
				{
					ChuvaPC.active=true;
				}
				else
				{
					ChuvaTablet.active=true;
				}
			}
			if(TempoActual==0)
			{
				Clouds.GetComponent.<AudioSource>().volume=0.2;
				Clouds.active=true;
				Trevoada.active=true;
				if(IsPC)
				{
					ChuvaPC.active=true;
				}
				else
				{
					ChuvaTablet.active=true;
				}
			}
		}
	}
}

function OnPlayerConnected(player: NetworkPlayer) {
	GetComponent.<NetworkView>().RPC("GetServerWeather",RPCMode.All,TempoActual);
}

@RPC
function GetServerWeather(ID:int)
{
	if(Network.isClient)
	{
		if(ID==1)
		{
			Clouds.GetComponent.<AudioSource>().volume=0;
			Clouds.active=false;
			Trevoada.active=false;
			if(IsPC)
			{
				ChuvaPC.active=false;
			}
			else
			{
				ChuvaTablet.active=false;
			}
		}
		if(ID==2)
		{
			Clouds.GetComponent.<AudioSource>().volume=0;
			Clouds.active=true;
			Trevoada.active=false;
			if(IsPC)
			{
				ChuvaPC.active=false;
			}
			else
			{
				ChuvaTablet.active=false;
			}
		}
		if(ID==3)
		{
			Clouds.GetComponent.<AudioSource>().volume=0.06;
			Clouds.active=true;
			Trevoada.active=false;
			if(IsPC)
			{
				ChuvaPC.active=true;
			}
			else
			{
				ChuvaTablet.active=true;
			}
		}
		if(ID==0)
		{
			Clouds.GetComponent.<AudioSource>().volume=0.2;
			Clouds.active=true;
			Trevoada.active=true;
			if(IsPC)
			{
				ChuvaPC.active=true;
			}
			else
			{
				ChuvaTablet.active=true;
			}
		}
	}
}